#!/usr/bin/env node
/**
 * Select a pillar and topic for the next moyo channel script.
 * Script content itself is generated by Claude Code, not an API.
 *
 * Usage:
 *   node scripts/generate-script.js                     # auto-select pillar + topic
 *   node scripts/generate-script.js --pillar behavior   # specify pillar
 */

const fs = require('fs');
const path = require('path');
const { PILLARS, PILLAR_IDS, selectPillar, selectPillarWithDemand, selectTopic } = require('../utils/content-pillars');
const { loadUsedTopics } = require('../utils/script-generator');

const DEMAND_FILE = path.join(__dirname, '..', 'data', 'analysis', 'psychology-demand.json');

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = { pillarId: null, useDemand: false };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--pillar' && args[i + 1]) {
      opts.pillarId = args[i + 1];
      i++;
    } else if (args[i] === '--use-demand') {
      opts.useDemand = true;
    }
  }

  return opts;
}

/**
 * Build pillar demand multipliers from psychology-demand.json.
 * Normalizes opportunity scores to the 0.5-2.0 range.
 */
function loadDemandMultipliers() {
  if (!fs.existsSync(DEMAND_FILE)) return null;

  const data = JSON.parse(fs.readFileSync(DEMAND_FILE, 'utf8'));
  const opportunities = data.opportunities || [];

  // Group opportunity scores by pillar
  const pillarScores = {};
  for (const t of opportunities) {
    if (!t.pillar) continue;
    if (!pillarScores[t.pillar]) pillarScores[t.pillar] = [];
    pillarScores[t.pillar].push(t.opportunity);
  }

  // Average scores per pillar
  const avgScores = {};
  for (const [pillar, scores] of Object.entries(pillarScores)) {
    avgScores[pillar] = scores.reduce((a, b) => a + b, 0) / scores.length;
  }

  // Normalize to 0.5-2.0 range
  const values = Object.values(avgScores);
  if (values.length === 0) return null;
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;

  const multipliers = {};
  for (const [pillar, score] of Object.entries(avgScores)) {
    multipliers[pillar] = 0.5 + ((score - min) / range) * 1.5;
  }

  return multipliers;
}

function main() {
  const opts = parseArgs();

  // Select pillar
  let pillarId, pillar;
  if (opts.pillarId) {
    pillarId = opts.pillarId;
    pillar = PILLARS[pillarId];
    if (!pillar) {
      console.error(`Unknown pillar "${pillarId}". Available: ${PILLAR_IDS.join(', ')}`);
      process.exit(1);
    }
  } else if (opts.useDemand) {
    const multipliers = loadDemandMultipliers();
    if (!multipliers) {
      console.error('No demand data found. Run analyze-psychology-demand.js first.');
      process.exit(1);
    }
    console.log('Demand multipliers:', JSON.stringify(multipliers, null, 2));
    const selection = selectPillarWithDemand([], multipliers);
    pillarId = selection.id;
    pillar = selection.pillar;
  } else {
    const selection = selectPillar();
    pillarId = selection.id;
    pillar = selection.pillar;
  }

  // Select topic (avoiding used ones)
  const usedTopics = loadUsedTopics();
  const topic = selectTopic(pillar, usedTopics);

  console.log('=== moyo Script Topic Selection ===');
  console.log(`Pillar:       ${pillar.name} (${pillarId})`);
  console.log(`Topic:        ${topic}`);
  console.log(`Style guide:  ${pillar.styleGuide}`);
  console.log(`Used topics:  ${usedTopics.length} previously generated`);
  if (opts.useDemand) {
    console.log(`Demand data:  loaded from psychology-demand.json`);
  }
  console.log();
  console.log('Next step: Ask Claude Code to generate the script for this topic.');
}

main();
